# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric color
format 5 = "%F"
format 6 = " %y-%m-%d %R"
format A 10 2 5
format B 7 0 0
format C 7 3 0
format D 11 2 0
format E 6 3 0
format F 6 2 0
format H 27 2 0
color 1 = @white;@black
color 7 = @white;@blue
rightstring A0 = "date"
rightstring B0 = "milage"
rightstring C0 = "added"
rightstring D0 = "efficiency"
rightstring E0 = "price"
rightstring F0 = "cost"
rightstring G0 = "total"
let A1 = @dts(2016,3,27)
fmt A1 "%F"
let B1 = 8424
let C1 = 12.329
let D1 = (B1-@nval("B",@myrow-1))/C1
let E1 = 1.899
let F1 = 23.41
let G1 = @nval("G",@myrow-1)+F1
let A2 = @dts(2016,8,9)
fmt A2 "%F"
let B2 = 9183
let C2 = 12.329
let D2 = (B2-@nval("B",@myrow-1))/C2
let E2 = 1.899
let F2 = 23.41
let G2 = @nval("G",@myrow-1)+F2
let A3 = @dts(2016,11,1)
fmt A3 "%F"
let B3 = 9432
let C3 = 13.323
let D3 = (B3-@nval("B",@myrow-1))/C3
let E3 = 2.099
let F3 = 27.96
let G3 = @nval("G",@myrow-1)+F3
goto B2 A0
